/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.zenith.bitbite.api;

import com.zenith.bitbite.api.domain.UserId;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-16T20:44:14.459347600+02:00[Europe/Madrid]")
@Validated
@Tag(name = "Customers", description = "Customer management")
public interface CustomersApi {

    /**
     * POST /users : Texto de prueba
     * Descripción corregida
     *
     * @param userId Descripción requerida (required)
     * @return Solicitud exitosa (status code 200)
     */
    @Operation(
        operationId = "apiTest",
        summary = "Texto de prueba",
        tags = { "Customers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Solicitud exitosa", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserId.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<UserId> apiTest(
        @Parameter(name = "UserId", description = "Descripción requerida", required = true) @Valid @RequestBody UserId userId
    );

}
